[project]
name = "infra"
version = "0.1.0"
description = "Pyinfra state for OCA-FRANCE servers"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "load-dotenv>=0.1.0",
    "pyinfra>=3.5.1",
]
